version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws/aws-sdk-php
    versions:
    - 3.172.0
    - 3.172.4
    - 3.173.13
    - 3.173.18
    - 3.173.23
    - 3.173.28
    - 3.173.4
    - 3.173.8
    - 3.175.0
    - 3.176.2
    - 3.176.7
    - 3.178.1
    - 3.178.5
